# LiveGPT
#
# The following env variables must be set:
# GOOGLE_APPLICATION_CREDENTIALS musts be set to use the TTS & STT
# OPENAI_API_KEY musts be set to use the ChatCompletion
development: true
logging:
  json: false
  level: debug

livekit:
  url: wss://chattogpt-r9z71rqw.livekit.cloud
  api_key: API9Pf94wzL5mXT
  secret_key: z2TjNOKtKF41dY2cHbqCJjsBGG2tUXgcf97j6vvKjhV

openai_api_key: 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

port: 3001    
