# LiveGPT
#
# The following env variables must be set:
# GOOGLE_APPLICATION_CREDENTIALS musts be set to use the TTS & STT
# OPENAI_API_KEY musts be set to use the ChatCompletion
development: true
logging:
  json: false
  level: debug

livekit:
  url: ws://localhost:7880
  api_key: devkey
  secret_key: secret

openai_api_key: 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
port: 3001    
